name: CI/CD Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files
        run: |
          VERSION=${{ github.ref_name }}
          mkdir -p "./pages/${VERSION}"
          cp -r ./en "./pages/${VERSION}/"
          cp -r ./ru "./pages/${VERSION}/"
          cp ./index.html "./pages/${VERSION}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./pages
          keep_files: true
